version: '3.8'

services:
  backend:
    build:
      context: ./backend
      args:
        - VERSION=${VERSION}
    image: yourdockerhub/backend:${VERSION}
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/todos
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      args:
        - VERSION=${VERSION}
    image: yourdockerhub/frontend:${VERSION}
    ports:
      - '3000:3000'
    depends_on:
      - backend

  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
